# Generated by Django 2.1.4 on 2019-05-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=200)),
                ('loan_date', models.DateField(auto_now_add=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('compount_method', models.CharField(max_length=200)),
                ('application_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('case_fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('incident_date', models.DateField()),
            ],
        ),
    ]
