# Generated by Django 2.1.4 on 2019-05-01 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='fk_borrowers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='borrowers.Borrower', verbose_name='Borrowers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loans',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loans',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
