# Generated by Django 2.1.4 on 2019-05-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='social_security',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='state',
            field=models.CharField(blank=True, choices=[('NY', 'New York'), ('NJ', 'New Jersey')], default='NY', max_length=2),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='zip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
